#!/bin/bash
# Shell Script for new Mac computers which installs different tools as Git, Git-up, Brew, Atom, Zsh, Jekyll and setups Git Aliases and Git config.

echo "Installing tools for Praqma users"


# 1 Install HomeBrew first

echo "Installing HomeBrew"
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" </dev/null 2> /dev/null


# 2 Install Git after HomeBrew is installed
echo "Installing Git"
brew install git


# 3 Git Aliases
echo "Writing aliases into home/.gitconfig"
cat Aliases >> $HOME/.gitconfig


# Install git up
echo "Installing Git-up"
gem install git-up


# 4 Setup Git username and password
echo "Please insert your name and email as parameter when running installtools in quotation marks"
echo 'Example ./installtools "Sonny Singh" "sos@praqma.net"'

username="$1"
echo "Username contains $username"

mail="$2"
echo "Email contains $mail"

git config --global user.name "$username"
git config --global user.email "$mail"



# 5 Install Ruby gem GHI
echo "Installing GHI"
brew install ghi



# 6 Install Atom.io
echo "Installing Atom"
brew cask install atom



# 7 Install Zsh
echo "Installing Zsh"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"




# 8 Install Jekyll
echo "Installing Jekyll and Jekyll Redirect"
gem install jekyll
gem install jekyll-redirect-from
